// ───────────────────────────────────────────────────────────────────────────
// Core types for Chess Teacher
// ───────────────────────────────────────────────────────────────────────────

export type Color = 'white' | 'black'

/** Raw classification coming from chess.com (c_effect type / NAG). */
export type Classification =
  | 'Brilliant'
  | 'Great'
  | 'Best'
  | 'Excellent'
  | 'Good'
  | 'Book'
  | 'Inaccuracy'
  | 'Mistake'
  | 'Blunder'
  | 'Miss'

/** Category shown to the user (chess.com terms). */
export type Category = 'Inaccuracy' | 'Mistake' | 'Blunder' | 'Miss' | 'Excellent'

export type Phase = 'opening' | 'middlegame' | 'endgame'

/** A single move extracted from the PGN. */
export interface ParsedMove {
  ply: number // 1-based
  moveNumber: number
  color: Color
  san: string
  from: string
  to: string
  nag?: number
  comment?: string
  classification?: Classification
  fenBefore: string
  fenAfter: string
}

export interface ParsedGame {
  meta: GameMeta
  moves: ParsedMove[]
  gameId: string
  hasAnnotations: boolean
}

export interface GameMeta {
  event?: string
  white: string
  black: string
  date?: string
  eco?: string
  ecoUrl?: string
  result?: string
  link?: string
  whiteElo?: string
  blackElo?: string
  timeControl?: string
}

/** Best line (PV) computed by the engine from the mistake position. */
export interface EngineLine {
  sanMoves: string[]
  uciMoves: string[]
  fens: string[] // fen after each ply of the line (same length as sanMoves)
  froms: string[]
  tos: string[]
  depth: number
  evalCp?: number // centipawns, from the user's POV
  mate?: number // user's POV (>0 = user delivers mate)
}

export interface LessonVariationStep {
  move: string // SAN
  note: string
}

export type LessonHighlight =
  | { type: 'arrow'; from: string; to: string; color?: string }
  | { type: 'square'; square: string; color?: string }

/** Structured lesson generated by the Tutor (Claude). Text content is PT-BR. */
export interface Lesson {
  category: string
  conceptTags: string[]
  answer: string
  variation: LessonVariationStep[]
  highlights: LessonHighlight[]
}

/** A study point (one of the user's bad moves). */
export interface StudyPoint {
  id: string
  ply: number
  moveNumber: number
  color: Color
  san: string // the (bad) move the user played
  from: string
  to: string
  category: Category
  classification: Classification
  fenBefore: string
  fenAfter: string
  bestLine?: EngineLine
  evalBestCp?: number // user's POV
  evalBestMate?: number
  evalPlayedCp?: number // user's POV
  evalPlayedMate?: number
  cpLoss?: number
  lesson?: Lesson
  lessonError?: string
}

export interface ErrorTag {
  tag: string
  category: Category
  phase: Phase
  color: Color
}

export interface AnalyzedGame {
  id: string
  importedAt: number
  meta: GameMeta
  userColor: Color
  pgn: string
  points: StudyPoint[]
  errorTags: ErrorTag[]
}

export interface PatternFocus {
  title: string
  description: string
  tags: string[]
  color?: Color | 'both'
}

export interface PatternAnalysis {
  generatedAt: number
  basedOnGames: number
  summary: string
  focuses: PatternFocus[]
}

export type ClaudeModel = 'claude-sonnet-4-6' | 'claude-opus-4-8' | 'claude-haiku-4-5-20251001'
